# Generated by Django 3.1.2 on 2020-10-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replies',
            new_name='Reply',
        ),
        migrations.AddField(
            model_name='answers',
            name='reply',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.reply'),
            preserve_default=False,
        ),
    ]
