# Generated by Django 3.0.3 on 2020-11-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_form_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
